import { useState } from 'react';
import { usePage, useForm } from '@inertiajs/react';
import PlatformLayout from '@/Layouts/PlatformLayout';

export default function AiTools({ tools }) {
    const { flash } = usePage().props;
    const { data, setData, put, processing } = useForm({ name: '', description: '', category: '', requires_confirmation: false, is_active: true });
    const [editing, setEditing] = useState(null);
    const categories = ['products', 'customers', 'leads', 'orders', 'escalation', 'tasks', 'knowledge'];
    const riskColors = { read: 'bg-blue-100 text-blue-700', write: 'bg-yellow-100 text-yellow-700', sensitive: 'bg-orange-100 text-orange-700', restricted: 'bg-red-100 text-red-700' };

    return (
        <PlatformLayout title="AI Tools">
            <h1 className="text-2xl font-bold text-gray-900 mb-6">Master Tool Catalogue</h1>
            <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden"><table className="w-full text-sm"><thead className="bg-gray-50"><tr><th className="text-left px-4 py-3 font-medium text-gray-500">Tool</th><th className="text-left px-4 py-3 font-medium text-gray-500">Identifier</th><th className="text-left px-4 py-3 font-medium text-gray-500">Category</th><th className="text-left px-4 py-3 font-medium text-gray-500">Risk</th><th className="text-left px-4 py-3 font-medium text-gray-500">Confirmation</th><th className="text-left px-4 py-3 font-medium text-gray-500">Status</th><th className="text-left px-4 py-3 font-medium text-gray-500">Actions</th></tr></thead><tbody className="divide-y divide-gray-100">{tools.map(t=>{const r=t.requires_confirmation?'sensitive':(t.category==='escalation'?'restricted':(t.category==='orders'?'write':'read'));const rl=r==='read'?'Read':r==='write'?'Write':r==='sensitive'?'Sensitive':'Restricted';return(<tr key={t.id}><td className="px-4 py-3 font-medium text-gray-900">{t.name}</td><td className="px-4 py-3 text-gray-500 text-xs font-mono">{t.identifier}</td><td className="px-4 py-3 text-gray-500 text-xs uppercase">{t.category}</td><td className="px-4 py-3"><span className={`px-2 py-0.5 rounded-full text-xs font-medium ${riskColors[r]||'bg-gray-100 text-gray-600'}`}>{rl}</span></td><td className="px-4 py-3 text-xs">{t.requires_confirmation?'Yes ✓':'No'}</td><td className="px-4 py-3"><span className={`px-2 py-0.5 rounded-full text-xs font-medium ${t.is_active?'bg-green-100 text-green-700':'bg-gray-100 text-gray-600'}`}>{t.is_active?'Active':'Inactive'}</span></td><td className="px-4 py-3"><button onClick={()=>{setEditing(t.id);setData({name:t.name,description:t.description,category:t.category,requires_confirmation:t.requires_confirmation,is_active:t.is_active})}} className="text-xs text-purple-600">Edit</button></td></tr>)})}</tbody></table></div>
            {editing&&(<form onSubmit={e=>{e.preventDefault();put(`/platform/tools/${editing}`,{onSuccess:()=>setEditing(null)})}} className="mt-6 bg-white rounded-xl shadow-sm border border-gray-200 p-6 max-w-lg"><h3 className="font-semibold mb-3">Edit Tool</h3><div className="grid grid-cols-2 gap-3"><input value={data.name} onChange={e=>setData('name',e.target.value)} className="px-3 py-2 border rounded text-sm" placeholder="Name" required /><select value={data.category} onChange={e=>setData('category',e.target.value)} className="px-3 py-2 border rounded text-sm">{categories.map(c=><option key={c} value={c}>{c}</option>)}</select><input value={data.description} onChange={e=>setData('description',e.target.value)} className="px-3 py-2 border rounded text-sm col-span-2" placeholder="Description" /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={data.requires_confirmation} onChange={e=>setData('requires_confirmation',e.target.checked)}/> Requires confirmation</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={data.is_active} onChange={e=>setData('is_active',e.target.checked)}/> Active</label></div><div className="flex gap-2 mt-3"><button type="submit" disabled={processing} className="px-4 py-2 bg-purple-600 text-white rounded text-sm">Save</button><button type="button" onClick={()=>setEditing(null)} className="px-4 py-2 border rounded text-sm">Cancel</button></div></form>)}
        </PlatformLayout>
    );
}