import { useState } from 'react';
import { Link, usePage, useForm } from '@inertiajs/react';
import PlatformLayout from '@/Layouts/PlatformLayout';

export default function TenantDetail({ organization, aiUsage, plans }) {
    const { flash } = usePage().props;
    const { post } = useForm();
    const [showSupport, setShowSupport] = useState(false);
    const [showPlanChange, setShowPlanChange] = useState(false);
    const [showBudgetEdit, setShowBudgetEdit] = useState(false);
    const [showAddUser, setShowAddUser] = useState(false);
    const supportForm = useForm({ reason: '' });
    const planForm = useForm({ plan_id: '' });
    const budgetForm = useForm({ monthly_ai_budget_cents: organization.monthly_ai_budget_cents ? (organization.monthly_ai_budget_cents / 100) : '' });
    const addUserForm = useForm({ user_email: '', role: 'user' });
    const plan = organization.subscriptions?.[0]?.plan;
    const currentBudget = organization.monthly_ai_budget_cents ? (organization.monthly_ai_budget_cents / 100) : null;

    return (
        <PlatformLayout title={`Organization — ${organization.name}`}>
            <div className="flex items-center justify-between mb-6">
                <div><Link href="/platform/tenants" className="text-sm text-gray-500 hover:text-gray-700 mb-1 inline-block">← Back</Link><h1 className="text-2xl font-bold text-gray-900">{organization.name}</h1></div>
                <div className="flex items-center gap-2">
                    <span className={`px-3 py-1 rounded-full text-sm font-medium ${organization.is_active?'bg-green-100 text-green-700':'bg-red-100 text-red-700'}`}>{organization.is_active?'Active':'Suspended'}</span>
                    <button onClick={()=>post(`/platform/tenants/${organization.id}/toggle`)} className={`text-sm px-3 py-1.5 rounded-lg ${organization.is_active?'bg-red-50 text-red-600':'bg-green-50 text-green-600'}`}>{organization.is_active?'Suspend':'Activate'}</button>
                </div>
            </div>
            <div className="grid grid-cols-3 gap-6">
                <div className="col-span-2 space-y-6">
<div className="bg-white rounded-xl shadow-sm border p-6"><h3 className="font-semibold mb-4">Profile</h3><div className="grid grid-cols-2 gap-4 text-sm"><div><span className="text-gray-500">Email:</span> {organization.email||'—'}</div><div><span className="text-gray-500">Phone:</span> {organization.phone||'—'}</div><div><span className="text-gray-500">Website:</span> {organization.website||'—'}</div><div><span className="text-gray-500">Industry:</span> {organization.industry||'—'}</div><div><span className="text-gray-500">Country:</span> {organization.country||'—'}</div><div><span className="text-gray-500">Currency:</span> {organization.currency||'USD'}</div><div><span className="text-gray-500">Created:</span> {new Date(organization.created_at).toLocaleDateString()}</div></div></div>
                    <div className="bg-white rounded-xl shadow-sm border p-6"><h3 className="font-semibold mb-4">Metrics</h3><div className="grid grid-cols-4 gap-4">{[{label:'Users',v:organization.users_count},{label:'AI Employees',v:organization.ai_employees_count},{label:'Customers',v:organization.customers_count},{label:'Conversations',v:organization.conversations_count},{label:'Leads',v:organization.leads_count},{label:'Orders',v:organization.orders_count},{label:'AI Cost MTD',v:`₦${aiUsage.cost}`},{label:'AI Runs MTD',v:aiUsage.runs?.toLocaleString()}].map(s=>(<div key={s.label} className="p-3 bg-gray-50 rounded-lg"><p className="text-lg font-bold">{s.v}</p><p className="text-xs text-gray-500">{s.label}</p></div>))}</div></div>
                </div>
                <div className="space-y-4">
                    <div className="bg-white rounded-xl shadow-sm border p-6"><h3 className="font-semibold mb-3">Subscription</h3><p className="text-sm">Plan: <span className="font-medium">{plan?.name||'None'}</span></p>{plan&&<p className="text-xs text-gray-400">₦${plan.price}/mo</p>}<button onClick={()=>setShowPlanChange(!showPlanChange)} className="mt-3 text-xs text-purple-600">Change Plan</button>{showPlanChange&&(<form onSubmit={e=>{e.preventDefault();planForm.post(`/platform/tenants/${organization.id}/plan`,{onSuccess:()=>setShowPlanChange(false)})}} className="mt-3 space-y-2"><select value={planForm.data.plan_id} onChange={e=>planForm.setData('plan_id',e.target.value)} className="w-full px-2 py-1.5 border rounded text-sm"><option value="">Select</option>{plans?.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="px-3 py-1.5 bg-purple-600 text-white rounded text-xs">Update</button></form>)}</div>
                    <div className="bg-white rounded-xl shadow-sm border p-6"><h3 className="font-semibold mb-3">Support Session</h3><p className="text-xs text-gray-500 mb-3">Access this org as support administrator.</p>{!showSupport?<button onClick={()=>setShowSupport(true)} className="w-full px-4 py-2 bg-purple-600 text-white rounded-lg text-sm">Access Customer Dashboard</button>:<form onSubmit={e=>{e.preventDefault();supportForm.post(`/platform/tenants/${organization.id}/support`)}}><textarea value={supportForm.data.reason} onChange={e=>supportForm.setData('reason',e.target.value)} className="w-full px-3 py-2 border rounded-lg text-sm mb-2" placeholder="Reason..." rows={3} required/><div className="flex gap-2"><button className="px-3 py-1.5 bg-purple-600 text-white rounded text-xs">Start</button><button type="button" onClick={()=>setShowSupport(false)} className="px-3 py-1.5 border rounded text-xs">Cancel</button></div></form>}</div>
                    <div className="bg-white rounded-xl shadow-sm border p-6"><h3 className="font-semibold mb-3">Team ({organization.users?.length||0})</h3><div className="space-y-2 mb-4">{organization.users?.map(u=>(<div key={u.id} className="text-sm flex justify-between"><span>{u.name} <span className="text-xs text-gray-400">({u.email})</span></span><span className="text-xs text-gray-400">{u.pivot?.role||'user'}</span></div>))}{organization.users?.length===0 && <p className="text-xs text-gray-400">No users assigned.</p>}</div>{!showAddUser ? <button onClick={()=>setShowAddUser(true)} className="text-xs text-purple-600 hover:text-purple-700">+ Add User</button> : <form onSubmit={e=>{e.preventDefault();addUserForm.post(`/platform/tenants/${organization.id}/add-user`,{onSuccess:()=>setShowAddUser(false)})}} className="space-y-2"><input type="email" value={addUserForm.data.user_email} onChange={e=>addUserForm.setData('user_email',e.target.value)} className="w-full px-2 py-1.5 border rounded text-sm" placeholder="User email address" required /><select value={addUserForm.data.role} onChange={e=>addUserForm.setData('role',e.target.value)} className="w-full px-2 py-1.5 border rounded text-sm"><option value="user">User</option><option value="admin">Admin</option></select><div className="flex gap-2"><button className="px-3 py-1.5 bg-purple-600 text-white rounded text-xs">Add</button><button type="button" onClick={()=>setShowAddUser(false)} className="px-3 py-1.5 border rounded text-xs">Cancel</button></div></form>}</div>
                    <div className="bg-white rounded-xl shadow-sm border p-6"><h3 className="font-semibold mb-3">🤖 AI Budget</h3><p className="text-sm mb-1">Monthly limit: <span className="font-medium">{currentBudget ? `₦${currentBudget}/mo` : 'Unlimited'}</span></p><p className="text-xs text-gray-500 mb-3">Spent this month: <span className="font-medium text-amber-600">{aiUsage.cost >= (currentBudget * 0.9 || 0) ? '⚠️ ' : ''}₦${aiUsage.cost}</span> ({(currentBudget ? Math.round(aiUsage.cost / currentBudget * 100) : 0)}% used)</p>{!showBudgetEdit ? <button onClick={() => setShowBudgetEdit(true)} className="text-xs text-purple-600 hover:text-purple-700">{currentBudget ? 'Change' : 'Set Budget'}</button> : <form onSubmit={e => { e.preventDefault(); budgetForm.post(`/platform/tenants/${organization.id}/budget`, { onSuccess: () => setShowBudgetEdit(false) }); }} className="mt-3 space-y-2"><input type="number" value={budgetForm.data.monthly_ai_budget_cents} onChange={e => budgetForm.setData('monthly_ai_budget_cents', e.target.value)} step="0.01" min="0" className="w-full px-2 py-1.5 border rounded text-sm" placeholder="Monthly budget (₦)" /><div className="flex gap-2"><button className="px-3 py-1.5 bg-purple-600 text-white rounded text-xs">Save</button><button type="button" onClick={() => setShowBudgetEdit(false)} className="px-3 py-1.5 border rounded text-xs">Cancel</button></div></form>}</div>
                </div>
            </div>
        </PlatformLayout>
    );
}